### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by Tienisto**
I am using the prerelease for quite some while and it seems to work.
Please release the stable version, so that other packages can depend on it :)

### CODE REVIEW

**Comment by edgarfroes** [comment]
Is the owner of this repo still in the business? Maybe it's time for us to recreate this package.

**Review by nitehogg — APPROVED** [review]

**Comment by nitehogg** [comment]
Keep your pants on @edgarfroes

**Comment by edgarfroes** [comment]
@nitehogg too late, they're already down for you.

**Comment by gspencergoog** [comment]
@nitehogg any ETA of when you might be submitting and publishing this?  Other packages can't finish null safety migration if they depend on this package until there's a stable null-safe version.

**Comment by nitehogg** [comment]
Sorry for the delay. It's published.

**Pull request merged**
